### ISSUE TITLE
High Pitched Whine in Motocross Championship

### ISSUE THREAD

**Issue by twinfami** [MiSTer-devel/S32X_MiSTer#14]
Throughout the game, there is a steady high pitched beep or whine that won't go away at all

**Comment by a-barone** [comment]
S32X Core version:
Release 20220607

Hi!
**I can confirm that this issue has been fixed and cannot be reproduced anymore.**
Here's the evidence:
**Real Hardware (Left) | S32X Core (Right)**
https://youtu.be/0hdru0YKyDs

Please, this issue can now be closed.
