### ISSUE TITLE
Glitchy floors and walls in Doom 32XR

### ISSUE THREAD

**Issue by viciious** [MiSTer-devel/S32X_MiSTer#18]
https://youtu.be/rIpAX-f50eI?t=2165

Note how the slime shines through the floor for a short moment. This happens at random points in the game with random floors and walls. Doesn't happen on original hardware.

Possible culprits may include:
- stale shared 32X register values
- TAS command implementation problems
- cache-through access not working properly

**Comment by rodrigomolinsky** [comment]
Just to add an example, I played again today and the problem persists.

https://www.youtube.com/watch?v=h9HxiEmd1sc

**Comment by a-barone** [comment]
I can confirm that this issue still occurs with the S32X_20220607 core. Same glitches and behavior.

**Comment by mario-64** [comment]
Doom 32X Resurrection v2.1 has been released with many bug fixes. It would be worth re-testing this version on the MiSTer core. Perhaps the issue referenced here is actually a patch bug.

**Comment by viciious** [comment]
> Doom 32X Resurrection v2.1 has been released with many bug fixes. It would be worth re-testing this version on the MiSTer core. Perhaps the issue referenced here is actually a patch bug.

I'm the main programmer behind D32XR and no, the issue is a 32X core bug.

**Comment by mario-64** [comment]
> > Doom 32X Resurrection v2.1 has been released with many bug fixes. It would be worth re-testing this version on the MiSTer core. Perhaps the issue referenced here is actually a patch bug.
> 
> I'm the main programmer behind D32XR and no, the issue is a 32X core bug.

Oh ok. My bad. Sorry.

**Comment by a-barone** [comment]
Here's a side-by-side recording of a real hardware Genesis 32X setup (left) vs the S32X core (right):
https://www.youtube.com/watch?v=SVP9ScL2pjg

You can see that it only glitches on the S32X core and both are running the very same ROM file.

**Comment by M-Walrus** [comment]
There is also an issue with the map screen in this hack, when used with the latest version of the core.  This happened on the older core version also, and shows as glitchy horizontal and vertical lines on the screen randomly appearing when moving the map around or zooming in/out (hold b and then press up/down for zoom)

I also hear the stereo sounds sometimes in seemingly the wrong channel, which can be disorienting.

I've not confirmed that either of these occur on the original 32X but thought they were worth mention here, given this hack of Doom is a stand-out development effort for the 32X.

**Comment by viciious** [comment]
> I also hear the stereo sounds sometimes in seemingly the wrong channel, which can be disorienting.

This is most likely a game bug. Anyway, please let's stay on topic.

**Comment by a-barone** [comment]
> @a-barone can you try with this build?
[S32X_20221108.zip](https://github.com/MiSTer-devel/S32X_MiSTer/files/9969081/S32X_20221108.zip)

_Originally posted by @thehughhefner in https://github.com/MiSTer-devel/S32X_MiSTer/issues/37#issuecomment-1308404421_

@viciious @M-Walrus 
All graphical glitches, reported in this issue - including the automap ones - seem to have been fixed with the 20221108 build provided by @thehughhefner.

Glitches still present in the latest official release:
Real Hardware (Left) | S32X Core (Right) (Release 20221002)
https://www.youtube.com/watch?v=YCwdshHIm4U

Glitches fixed in the 20221108 build:
Real Hardware (Left) | S32X Core (Right) 
https://www.youtube.com/watch?v=o6tvRfQ-wvY

**Comment by asturur** [comment]
All the glitches mentioned in this issue seems to have been fixed with the november release

**Comment by Toryalai1** [comment]
@viciious Users mention that this issue is now fixed. Can you close this ticket?
