### ISSUE TITLE
Motorcross championship europe/usa 

### ISSUE THREAD

**Issue by pplatoon** [MiSTer-devel/S32X_MiSTer#21]
in this game you can hear a constant beeping sound that is very annoying

**Comment by thehughhefner** [comment]
This issue has been fixed by this pull request. 
https://github.com/MiSTer-devel/S32X_MiSTer/pull/22

**Comment by a-barone** [comment]
2X Core version:
Release 20220607

Hi!
I can confirm that this issue has been fixed and cannot be reproduced anymore.
Here's the evidence:
Real Hardware (Left) | S32X Core (Right)
https://youtu.be/0hdru0YKyDs

Please, this issue can now be closed along with https://github.com/MiSTer-devel/S32X_MiSTer/issues/14.
