### ISSUE TITLE
Core loads Megadrive/Genesis games from previous core memory

### ISSUE THREAD

**Issue by PhantombrainM** [MiSTer-devel/S32X_MiSTer#23]
I played Sonic 1 PAL on Megadrive Core.

Then I launched the 32X Core. It boots up with Sonic 1 from the previous core.

**Comment by Toryalai1** [comment]
I cannot recreate this
@PhantombrainM Could you revisit this issue?

**Comment by sorgelig** [comment]
It's not an issue. If SDRAM is dirty, then core may execute the code from it. Especially these cores have same memory layout.
