### ISSUE TITLE
32X Core - "Spider-Man Web of Fire" - SH2 exception right on the first level

### ISSUE THREAD

**Issue by rodrigomolinsky** [MiSTer-devel/S32X_MiSTer#27]
![image](https://user-images.githubusercontent.com/104881214/166620302-c5fbc985-f90f-4c4f-bf40-d63fe7929b22.png)

The game can't be played. While you're in title screens and menus, it works ok. But right after starting the first level, the game freezes and there is a error being displayed on the screen:

> _SH2 Engine Error: CQue_ProcessOne: cque_to_call invalid_

It happened on the first day of the core, so I waited an update. After updating today (May 3rd), the error persists.

**Comment by trebor68** [comment]
If it helps narrow down the issue, the same happened to me after Spider-Man was knocked off the ledge of a building, clung to the side, and started crawling back up:

![WebOfFire](https://user-images.githubusercontent.com/8142518/167024479-c661f518-7ab7-47cb-8f4a-fd8cda652bbd.PNG)

**Comment by rodrigomolinsky** [comment]
Another example to reproduce the problem: I was also knocked off from a building and was saved by the error:

![image](https://user-images.githubusercontent.com/104881214/172020466-5302955c-a470-4d34-b5a9-7dbf7ae7f61a.png)

**Comment by thehughhefner** [comment]
This issue has already been reported and is related to this: https://github.com/MiSTer-devel/S32X_MiSTer/issues/9
Try with this build: 
[S32X.zip](https://github.com/MiSTer-devel/S32X_MiSTer/files/8852347/S32X.zip)
