### ISSUE TITLE
32X Core - "X-Men Prototype" - Glitchy textures

### ISSUE THREAD

**Issue by rodrigomolinsky** [MiSTer-devel/S32X_MiSTer#28]
For reference, here is how the game should look like:

https://www.youtube.com/watch?v=uQNaRTxDWQU

But the perspective of the textures from the walls and platforms are not corrected, they are flat.
I recorded some videos to illustrate (I'm sorry about my camera work):

https://user-images.githubusercontent.com/104881214/166621102-ff5a7cec-a9fc-416a-aad0-c59eba8ecc1c.MOV

https://user-images.githubusercontent.com/104881214/166621157-a2428982-d5c0-4bb1-8986-0b83ab324a23.MOV

**Comment by asturur** [comment]
Seems fixed in https://github.com/MiSTer-devel/S32X_MiSTer/pull/45.
Please try the attached rbf if you want

**Comment by Toryalai1** [comment]
This can be closed
