### ISSUE TITLE
Video Processing - Should be rename Blast Processing

### ISSUE THREAD

**Issue by TT-Hipster1941** [MiSTer-devel/S32X_MiSTer#29]
As 32x veterans we have no use for the puny Video Processing, Blast Processing it is!!

Please feel free to mention the Tower of Power somewhere to make sure we feel the stacking power of the hardware to complete our hardware immersion.

**Comment by RetroInVitro** [comment]
I support this useless petition as much as its utility!

**Comment by sorgelig** [comment]
Please go to MiSTer forum for chatting and share experience.
