### ISSUE TITLE
Pinocchio Protype missing a layer

### ISSUE THREAD

**Issue by asturur** [MiSTer-devel/S32X_MiSTer#30]
The pinocchio prototype, compared to what is visible on other emulators, is missing a full layer of parallax scrolling that appear black.

**Comment by asturur** [comment]
Glad to see a commit related to this issue.

**Comment by asturur** [comment]
With the lastest update, the games shows all the layers.
Thank you. We can close this issue.

**Comment by mario-64** [comment]
> With the lastest update, the games shows all the layers. Thank you. We can close this issue.
Since you opened the issue I'm pretty sure you need to close it.  :-)

**Comment by a-barone** [comment]
S32X Core version:
Release 20220607

Hi!

**I can confirm that this issue has been fixed and can be closed now.**
I played through all levels of the game and also recorded it during the final boss and ending + credits on the S32X Core while running side-by-side with a real Genesis 32X setup:
Real Hardware (Left) | S32X Core (Right)
https://youtu.be/PMsBei87o_s

I used this ROM for the tests:
https://hiddenpalace.org/Pinocchio_32x_(Dec_6,_1995_prototype)

**Comment by wwark** [comment]
@asturur  you cloud close it because you are the one opened it !
Thanks.

**Comment by asturur** [comment]
sure!
