### ISSUE TITLE
Pitfall: The Mayan Adventure - Sprites glitch near the horizontal borders of the screen

### ISSUE THREAD

**Issue by a-barone** [MiSTer-devel/S32X_MiSTer#39]
S32X Core version:
Release 20220607

Hi!
First I recorded footage of the S32X core running side-by-side with a real Genesis 32X setup:
Real Hardware (Left) | S32X Core (Right)
https://youtu.be/xSrc6kJZXm4

And in the following videos I focused only on the S32X core since this issue doesn't occur on real hardware:
https://youtu.be/GIZ1MQBojqM
https://youtu.be/RGoJiKvYzAY
https://youtu.be/XFs1bCCoLY8
https://youtu.be/bq6PsuHgclw
https://youtu.be/ryGk_WXvUx4

![image](https://user-images.githubusercontent.com/19418951/174456586-4d4b4d3d-86e2-4290-8233-0d736cdfcbb8.png)

**Comment by mario-64** [comment]
Could you please test using the latest build S32X_20221108?

**Comment by a-barone** [comment]
> Could you please test using the latest build S32X_20221108?
Yes, I'll record the test tomorrow (Monday) and post it here.

**Comment by a-barone** [comment]
> Could you please test using the latest build S32X_20221108?
I've tested it with that most recent build and the glitch is still there:
https://www.youtube.com/watch?v=1u86Y2ssOug

**Comment by mario-64** [comment]
Ok Thanks for checking.

**Comment by asturur** [comment]
bug is still there with build from #45

**Comment by asturur** [comment]
need check with commit 8a08913

**Comment by asturur** [comment]
With commit https://github.com/MiSTer-devel/S32X_MiSTer/commit/8a089136d1d61ac7cf064d3f2db408e07628ae63 this was fixed at least in first stage where the issue was already abundantly visible.

Thanks @srg320

**Comment by a-barone** [comment]
> With commit [8a08913](https://github.com/MiSTer-devel/S32X_MiSTer/commit/8a089136d1d61ac7cf064d3f2db408e07628ae63) this was fixed at least in first stage where the issue was already abundantly visible.
> 
> Thanks @srg320
If there's a partial build available, I can test the whole game for you guys.

**Comment by asturur** [comment]
https://github.com/MiSTer-unstable-nightlies/S32X_MiSTer/releases/download/unstable-builds/S32X_unstable_20230415_072c29.rbf

this is the latest commit built

**Comment by Toryalai1** [comment]
> > With commit [8a08913](https://github.com/MiSTer-devel/S32X_MiSTer/commit/8a089136d1d61ac7cf064d3f2db408e07628ae63) this was fixed at least in first stage where the issue was already abundantly visible.
> > Thanks @srg320
> 
> If there's a partial build available, I can test the whole game for you guys.

Did you try with latest build? https://github.com/MiSTer-unstable-nightlies/S32X_MiSTer/releases/download/unstable-builds/S32X_unstable_20230417_167dc3.rbf

**Comment by asturur** [comment]
this seems definitely fixed to me.

**Comment by a-barone** [comment]
Hi! I'm playing the game now and will finish testing it today and will post the feedback here.
Sorry for the delay but I had an unexpected trip last week.

**Comment by a-barone** [comment]
Hi again!

Finally checked the whole game and it's fine. This issue has been fixed.
Thanks a lot! 
You can close this issue now.
