### ISSUE TITLE
Color Balance issues on 20220421 release 

### ISSUE THREAD

**Issue by Dasutin** [MiSTer-devel/S32X_MiSTer#4]
Color balance issues in a gray ramp test, and color chart test on the 20220421 release. MiSTer does not have any video processing filters turned on.  Core is using the default settings. Seeing it on both HDMI and Analog out (RGB).  Test was done on the 32X 240p Test Suite.  Tests are displayed on the 32X layer. 

Gray Ramp - S32X Core
![MisterS32X_Grayramp](https://user-images.githubusercontent.com/820735/164339215-e39f7182-34e5-46ce-92f3-51ffd20a6b51.png)
Color Bars - S32X Core
![MisterS32X_Colorbars](https://user-images.githubusercontent.com/820735/164339229-c47b9b8e-693f-4484-a740-bfbca89f063d.png)

Gray Ramp - Sega 32X
![32X_Grayramp](https://user-images.githubusercontent.com/820735/164339342-abb6eed9-2f6a-469b-a7a8-a50daa078f48.png)
Color Bars - Sega 32X 
![32X_Colorbars](https://user-images.githubusercontent.com/820735/164339505-58aa10e9-a6fc-49d6-8539-708d8ec2e2af.png)

**Comment by Kitrinx** [comment]
[S32X.zip](https://github.com/MiSTer-devel/S32X_MiSTer/files/8526293/S32X.zip)
could you see if this build resolves your issue?

**Comment by Dasutin** [comment]
Looks like it's fixed.  Thanks for the fast turnaround!

Gray Ramp - S32X Core (Corrected Build)
![MisterS32X_Grayramp_corrected](https://user-images.githubusercontent.com/820735/164350643-364bd090-8b39-48fb-bee1-237cfa356fd8.png)

Color Bars - S32 Core (Corrected Build)
![MisterS32X_Colorbars_corrected](https://user-images.githubusercontent.com/820735/164350693-525452f4-4314-47b7-a5b0-ab10f993556b.png)

**Comment by mic-** [comment]
The attched build from @Kitrinx appears to solve the PWM audio playback speed problems I was experiencing with the initial release.

**Comment by thehughhefner** [comment]
This issue can be closed thanks to this:
https://github.com/MiSTer-devel/S32X_MiSTer/pull/5#issue-1210372507
