### ISSUE TITLE
SNAC not working

### ISSUE THREAD

**Issue by rennelu** [MiSTer-devel/S32X_MiSTer#40]
I've tried out SNAC using the misterfpga UK USB adapter board with the Sega controller adapter. I have Serial set to SNAC in the core, but neither my 3 button or 6 button controller is registering inputs. I tested them both in the Genesis core and have no issues. Is there something additional I need to do to enable SNAC in the core?

**Comment by misteraddons** [comment]
SNAC works in the latest release of the core. I just tested it myself :)

**Comment by rennelu** [comment]
Thanks for the confirmation. On further testing, it was working for some games and not others. Enabling "Swap Joysticks" in the menu fixed it for me, sorry about that.
