### ISSUE TITLE
Graphic corrupting on Primal Rage title screen

### ISSUE THREAD

**Issue by goldenegg** [MiSTer-devel/S32X_MiSTer#43]
On the title screen for Primal Rage, the section that says 'Rage' is corrupt.

**Comment by a-barone** [comment]
I cannot reproduce the issue reported by @goldenegg.
It seems to be working fine actually.

S32X Core version:
Release 20221002

Real Hardware (Left) | S32X Core (Right)
https://www.youtube.com/watch?v=4NFvp60VhV0

**Comment by Toryalai1** [comment]
If this is not reproducible then this ticket can be closed
