### ISSUE TITLE
Can support for .bin rom file extension be added?

### ISSUE THREAD

**Issue by silverflat** [MiSTer-devel/S32X_MiSTer#46]
I know this sounds trivial, but this would allow those that use a retrode2 to not have to update the config file on a computer every time we switch from genesis to 32x

**Comment by asturur** [comment]
is it just a different extension or a different rom format?

**Comment by silverflat** [comment]
It is just a different extension

**Comment by asturur** [comment]
i can open a pr for this is a simple task. Do you have a valid bin free opensource rom you can share with me in private ?

**Comment by sorgelig** [comment]
bin file extension is reserved for geneasis/megadrive ROM. So if/when core will able to fully support geneasis/megadrive ROMS then it will switch automatically depending on file extension.

**Comment by asturur** [comment]
The framework reserve a particular loading mechanism by extension?

**Comment by sorgelig** [comment]
It's not framework reserve. It's up to specific core how extensions are defined. For 32x with ~40 roms it should be a problem to rename them to 32x and forget. 
It's possible that 32x will be merged into MD core as a single core where extension will define the mode.

**Comment by asturur** [comment]
So let's close this issue as resolved/ won'tfix
