### ISSUE TITLE
Flicking Sprites in the HUD in Spider-Man Web of Fire (U)

### ISSUE THREAD

**Issue by Jlmbles** [MiSTer-devel/S32X_MiSTer#52]
Sprites remain in the HUD at the bottom of the screen and flicker.

**Comment by asturur** [comment]
@Jlmbles  how do you reproduce this? i can't see any flickering

**Comment by Zet-sensei** [comment]
I can't seem to reproduce the issue with core version 2024-09-02 after a quick test.
