### ISSUE TITLE
32x 3D tech demo

### ISSUE THREAD

**Issue by Breiztiger** [MiSTer-devel/S32X_MiSTer#56]
this demo freeze screen at start with last unstable build from 20240817

https://www.youtube.com/watch?v=LyjphvJOeH8&t=26s

**Comment by Zet-sensei** [comment]
For convenience.

Shinrinx-MARS by GF64
[shinrinx_final.zip](https://github.com/user-attachments/files/16647828/shinrinx_final.zip)

**Comment by Zet-sensei** [comment]
And the source code of the demo.

https://github.com/GenesisFan64/Shinrinx-MARS

**Comment by Breiztiger** [comment]
it the same on last repo build

**Comment by Zet-sensei** [comment]
Should be better now and even fixed with commit https://github.com/MiSTer-devel/S32X_MiSTer/commit/c8bf9be007b2ab2587b19c238161f629dd05edfd
