### ISSUE TITLE
Sound Pitch or Speed

### ISSUE THREAD

**Issue by neogeo81** [MiSTer-devel/S32X_MiSTer#7]
Some games have pitch or speed issue with some sound effects. Example Mortal Kombat II and Virtua Fighter.

**Comment by markriley83** [comment]
The star ward music is really fast, too

**Comment by viciious** [comment]
D32XR samples seem to have a higher than normal pitch as well

**Comment by viciious** [comment]
This seems to have been fixed a long time ago
