### ISSUE TITLE
Amazing Spider-Man, The - Web of Fire (USA) hang on first level

### ISSUE THREAD

**Issue by BarbieOnWeed** [MiSTer-devel/S32X_MiSTer#9]
The game hang on first level.
Amazing Spider-Man, The - Web of Fire (USA)
CRC: 29DCE257

![IMG_20220421_111050](https://user-images.githubusercontent.com/52424890/164453950-d9b95872-d532-4b83-99f2-a7f4b4ea8a9e.jpg)
)

**Comment by italiangrandma** [comment]
@BarbieOnWeed I just tested and reproduced the same error. Rom is the same CRC as yours.

**Comment by thehughhefner** [comment]
Can you try with this build? Extract and put the rbf file in media/fat/_Console folder
[S32X.zip](https://github.com/MiSTer-devel/S32X_MiSTer/files/8852333/S32X.zip)

**Comment by italiangrandma** [comment]
@thehughhefner should be able to test it tomorrow morning!

**Comment by italiangrandma** [comment]
@thehughhefner Ok, I was able to test it really quick and unfortunately I was still able to trigger the crash :(
